# Server settings  
server:  
    port:8080  
    address:localhost  
  
# DATASOURCE  
#jdbc:  
#    driverClass: com.mysql.jdbc.Driver  
#    url: jdbc:mysql://127.0.0.1:3306/local-kaishustory?useUnicode:true&characterEncoding:utf-8  
#    username: root  
#    password: admin  
  
# SPRING PROFILES  
spring:    
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: admin
    driver-class: com.mysql.jdbc.Driver     
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
  redis:
        master:127.0.0.1:6379
        nodes:10.4.1.14:26379
#jedis
jedis:
    pool:
        maxidl:20
        minidl:8
        maxtotal:500

# WeiXin Configuration  
weixin:  
    mp:  
       appid: xx  
       secret: ee  
       token: weixin  
       aeskey:  
  
# MyBatis  
mybatis:  
    typeAliasesPackage: com.modou.**.domain  
    mapperLocations: classpath:/com/modou/**/mapper/*.xml  
    configLocation: classpath:/mybatis-config.xml  
    
  